# Generated by Django 4.2.7 on 2024-02-15 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainees',
            fields=[
                ('discord_id', models.TextField(max_length=30, primary_key=True, serialize=False)),
                ('discord_pfp', models.TextField(max_length=150)),
                ('discord_name', models.TextField(max_length=30)),
                ('total_days', models.IntegerField(default=0)),
                ('total_problems', models.IntegerField(default=0)),
                ('highest_streak', models.IntegerField(default=0)),
                ('current_streak', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'trainees',
            },
        ),
        migrations.CreateModel(
            name='TraineeRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_id', models.TextField(max_length=30)),
                ('post_date', models.DateTimeField()),
                ('message', models.TextField(max_length=150)),
                ('streak', models.IntegerField(default=0)),
                ('today_problems', models.IntegerField(default=0)),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainee_records', to='api.trainees')),
            ],
            options={
                'db_table': 'trainee_records',
            },
        ),
    ]
