# Generated by Django 4.2.7 on 2024-02-17 12:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainee',
            fields=[
                ('discord_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('discord_pfp', models.URLField(max_length=550)),
                ('discord_name', models.CharField(max_length=50)),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_days', models.PositiveIntegerField(default=0)),
                ('total_problems', models.PositiveIntegerField(default=0)),
                ('highest_streak', models.PositiveIntegerField(default=0)),
                ('current_streak', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'trainee',
            },
        ),
        migrations.CreateModel(
            name='TraineeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_id', models.CharField(max_length=50)),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.TextField(max_length=550)),
                ('streak', models.PositiveIntegerField(default=0)),
                ('today_problems', models.PositiveIntegerField(default=0)),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainee_records', to='api.trainee')),
            ],
            options={
                'db_table': 'trainee_records',
                'unique_together': {('discord_id', 'post_date')},
            },
        ),
    ]
