# Generated by Django 4.2.7 on 2024-02-16 06:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainees',
            name='last_activity',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='traineerecords',
            name='post_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='traineerecords',
            name='streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='traineerecords',
            name='today_problems',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trainees',
            name='current_streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trainees',
            name='highest_streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trainees',
            name='total_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trainees',
            name='total_problems',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
