# Generated by Django 4.2.7 on 2024-02-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_trainees_last_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traineerecords',
            name='discord_id',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='traineerecords',
            name='message',
            field=models.TextField(max_length=550),
        ),
        migrations.AlterField(
            model_name='trainees',
            name='discord_id',
            field=models.TextField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trainees',
            name='discord_name',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='trainees',
            name='discord_pfp',
            field=models.TextField(max_length=550),
        ),
    ]
